### ISSUE TITLE
CUDA out of memory when checkpointing

### ISSUE THREAD

**Issue by arunpatala** [xgastaldi/shake-shake#2]
Hi,

When running the code the model trains for 1 epoch without running out of memory but while checkpointing the first time it tries to make a copy in GPU (not CPU mode). I guess there is a reason to change from default checkpointing done in fb.resnet.torch. Can you please explain the reason.

Thanks

**Comment by xgastaldi** [comment]
Contrary to the preresnet.lua code, there are some batchnorms in a seperate module (shakeshakeblock.lua). This creates a problem when testing a model because the batchnorm stats are not correctly saved by deepcopy (if some BNs are in a seperate module). You can see that by doing the following tests:
1. Change back to model = deepCopy(model):float():clearState() in checkpoints.lua, run the code for 1 epoch and test it with -testOnly: The test will give you a wrong result
2. Change back to model = deepCopy(model):float():clearState() in checkpoints.lua, remove/hide the batchnorms in shakeshakeblock.lua, run the code for 1 epoch and test it with -testOnly: The test should give you the right result

The only hack I managed to find is to replace model = deepCopy(model):float():clearState() by model = model:clone():clearState() but as mentionned by meliketoy in https://github.com/facebook/fb.resnet.torch/issues/141 this actually copies the model in the GPU level, so if your model takes up most of your GPU RAM, the program will be facing an 'out of memory' error.

**Comment by arunpatala** [comment]
Yeah that could be the problem. Having two copies of the model in GPU can consume the memory. Will try the test. Thanks.

**Comment by xgastaldi** [comment]
This commit should solve this issue: https://github.com/xgastaldi/shake-shake/commit/f4eb71428eebb0cd5ba2f91d40c477145a1a051e

I found a fix by using the deepcopy function of the lua-stdlib library. Please note that you might have to install stdlib if it is not already installed on your computer.
```
luarocks install stdlib
```
I also forgot to mention that you should set -optnet=false when testing a model otherwise you will not get the correct error rate.

If you update "shake-shake" this should be fixed now. Please comment if you still see the issue
